export const dataEmployees = [
    {
      name: {
        firstName: 'John',
        lastName: 'Doe',
      },
      startDate: '2018-01-01',
      department: 'Sales',
      dateOfBirth: '1980-01-01',
      address: '261 Erdman Ford',
      city: 'East Daphne',
      state: 'Kentucky',
      zipCode: '21037',
    },
    {
      name: {
        firstName: 'Jane',
        lastName: 'Doe',
      },
      startDate: '2019-01-01',
      department: 'Sales',
      dateOfBirth: '1981-01-01',
      address: '769 Dominic Grove',
      city: 'Columbus',
      state: 'Ohio',
      zipCode: '43215',
    },
    {
      name: {
        firstName: 'Joe',
        lastName: 'Doe',
      },
      startDate: '2020-01-01',
      department: 'Sales',
      dateOfBirth: '1982-01-01',
      address: '566 Brakus Inlet',
      city: 'South Linda',
      state: 'West Virginia',
      zipCode: '24751',
    },
    {
      name: {
        firstName: 'Kevin',
        lastName: 'Vandy',
      },
      startDate: '2014-01-01',
      department: 'Sales',
      dateOfBirth: '1983-01-01',
      address: '722 Emie Stream',
      city: 'Lincoln',
      state: 'Nebraska',
      zipCode: '68516',
    },
    {
      name: {
        firstName: 'Joshua',
        lastName: 'Rolluffs',
      },
      startDate: '2015-01-01',
      department: 'Sales',
      dateOfBirth: '1984-01-01',
      address: '32188 Larkin Turnpike',
      city: 'Charleston',
      state: 'South Carolina',
      zipCode: '29401',
    },
  ];